CREATE TABLE Users (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Pass VARCHAR(100) NOT NULL
);

CREATE TABLE Bills (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Company VARCHAR(255) NOT NULL,
    Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Files (
    Id SERIAL PRIMARY KEY,
    FilePath TEXT,
    FileSize BIGINT,
    Name TEXT,
    ParentId TEXT,
    IsDirectory BOOLEAN
);

